image:
  file: .gitpod.Dockerfile

tasks:
  - init: |
      docker-compose pull
      cd memex
      mix local.hex --force
      mix local.rebar --force
      mix deps.get --force
      mix ecto.migrate
      cd assets && yarn && cd ..
    env:
      PRINT_ME: "Hello World!"
      POSTGRES_DSN: "postgresql://postgres:memex@localhost:65432/memex"
    command: |
      iex -S mix phx.server
